/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as HowItWorksRouteImport } from './routes/how-it-works'
import { Route as GuaranteeRouteImport } from './routes/guarantee'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedPortalIndexRouteImport } from './routes/_authenticated/portal.index'
import { Route as AuthenticatedPortalInboxRouteImport } from './routes/_authenticated/portal.inbox'
import { Route as AuthenticatedPortalLibraryIndexRouteImport } from './routes/_authenticated/portal.library.index'
import { Route as AuthenticatedPortalClientsIndexRouteImport } from './routes/_authenticated/portal.clients.index'
import { Route as AuthenticatedPortalLibraryIdRouteImport } from './routes/_authenticated/portal.library.$id'
import { Route as AuthenticatedPortalClientsIdRouteImport } from './routes/_authenticated/portal.clients.$id'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const HowItWorksRoute = HowItWorksRouteImport.update({
  id: '/how-it-works',
  path: '/how-it-works',
  getParentRoute: () => rootRouteImport,
} as any)
const GuaranteeRoute = GuaranteeRouteImport.update({
  id: '/guarantee',
  path: '/guarantee',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedPortalIndexRoute =
  AuthenticatedPortalIndexRouteImport.update({
    id: '/portal/',
    path: '/portal/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPortalInboxRoute =
  AuthenticatedPortalInboxRouteImport.update({
    id: '/portal/inbox',
    path: '/portal/inbox',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPortalLibraryIndexRoute =
  AuthenticatedPortalLibraryIndexRouteImport.update({
    id: '/portal/library/',
    path: '/portal/library/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPortalClientsIndexRoute =
  AuthenticatedPortalClientsIndexRouteImport.update({
    id: '/portal/clients/',
    path: '/portal/clients/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPortalLibraryIdRoute =
  AuthenticatedPortalLibraryIdRouteImport.update({
    id: '/portal/library/$id',
    path: '/portal/library/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPortalClientsIdRoute =
  AuthenticatedPortalClientsIdRouteImport.update({
    id: '/portal/clients/$id',
    path: '/portal/clients/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/guarantee': typeof GuaranteeRoute
  '/how-it-works': typeof HowItWorksRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/portal/inbox': typeof AuthenticatedPortalInboxRoute
  '/portal/': typeof AuthenticatedPortalIndexRoute
  '/portal/clients/$id': typeof AuthenticatedPortalClientsIdRoute
  '/portal/library/$id': typeof AuthenticatedPortalLibraryIdRoute
  '/portal/clients/': typeof AuthenticatedPortalClientsIndexRoute
  '/portal/library/': typeof AuthenticatedPortalLibraryIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/guarantee': typeof GuaranteeRoute
  '/how-it-works': typeof HowItWorksRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/portal/inbox': typeof AuthenticatedPortalInboxRoute
  '/portal': typeof AuthenticatedPortalIndexRoute
  '/portal/clients/$id': typeof AuthenticatedPortalClientsIdRoute
  '/portal/library/$id': typeof AuthenticatedPortalLibraryIdRoute
  '/portal/clients': typeof AuthenticatedPortalClientsIndexRoute
  '/portal/library': typeof AuthenticatedPortalLibraryIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/guarantee': typeof GuaranteeRoute
  '/how-it-works': typeof HowItWorksRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/_authenticated/portal/inbox': typeof AuthenticatedPortalInboxRoute
  '/_authenticated/portal/': typeof AuthenticatedPortalIndexRoute
  '/_authenticated/portal/clients/$id': typeof AuthenticatedPortalClientsIdRoute
  '/_authenticated/portal/library/$id': typeof AuthenticatedPortalLibraryIdRoute
  '/_authenticated/portal/clients/': typeof AuthenticatedPortalClientsIndexRoute
  '/_authenticated/portal/library/': typeof AuthenticatedPortalLibraryIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/auth'
    | '/contact'
    | '/guarantee'
    | '/how-it-works'
    | '/pricing'
    | '/privacy'
    | '/reset-password'
    | '/sitemap.xml'
    | '/terms'
    | '/portal/inbox'
    | '/portal/'
    | '/portal/clients/$id'
    | '/portal/library/$id'
    | '/portal/clients/'
    | '/portal/library/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/auth'
    | '/contact'
    | '/guarantee'
    | '/how-it-works'
    | '/pricing'
    | '/privacy'
    | '/reset-password'
    | '/sitemap.xml'
    | '/terms'
    | '/portal/inbox'
    | '/portal'
    | '/portal/clients/$id'
    | '/portal/library/$id'
    | '/portal/clients'
    | '/portal/library'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/about'
    | '/auth'
    | '/contact'
    | '/guarantee'
    | '/how-it-works'
    | '/pricing'
    | '/privacy'
    | '/reset-password'
    | '/sitemap.xml'
    | '/terms'
    | '/_authenticated/portal/inbox'
    | '/_authenticated/portal/'
    | '/_authenticated/portal/clients/$id'
    | '/_authenticated/portal/library/$id'
    | '/_authenticated/portal/clients/'
    | '/_authenticated/portal/library/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
  AuthRoute: typeof AuthRoute
  ContactRoute: typeof ContactRoute
  GuaranteeRoute: typeof GuaranteeRoute
  HowItWorksRoute: typeof HowItWorksRoute
  PricingRoute: typeof PricingRoute
  PrivacyRoute: typeof PrivacyRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TermsRoute: typeof TermsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/how-it-works': {
      id: '/how-it-works'
      path: '/how-it-works'
      fullPath: '/how-it-works'
      preLoaderRoute: typeof HowItWorksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guarantee': {
      id: '/guarantee'
      path: '/guarantee'
      fullPath: '/guarantee'
      preLoaderRoute: typeof GuaranteeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/portal/': {
      id: '/_authenticated/portal/'
      path: '/portal'
      fullPath: '/portal/'
      preLoaderRoute: typeof AuthenticatedPortalIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/portal/inbox': {
      id: '/_authenticated/portal/inbox'
      path: '/portal/inbox'
      fullPath: '/portal/inbox'
      preLoaderRoute: typeof AuthenticatedPortalInboxRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/portal/library/': {
      id: '/_authenticated/portal/library/'
      path: '/portal/library'
      fullPath: '/portal/library/'
      preLoaderRoute: typeof AuthenticatedPortalLibraryIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/portal/clients/': {
      id: '/_authenticated/portal/clients/'
      path: '/portal/clients'
      fullPath: '/portal/clients/'
      preLoaderRoute: typeof AuthenticatedPortalClientsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/portal/library/$id': {
      id: '/_authenticated/portal/library/$id'
      path: '/portal/library/$id'
      fullPath: '/portal/library/$id'
      preLoaderRoute: typeof AuthenticatedPortalLibraryIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/portal/clients/$id': {
      id: '/_authenticated/portal/clients/$id'
      path: '/portal/clients/$id'
      fullPath: '/portal/clients/$id'
      preLoaderRoute: typeof AuthenticatedPortalClientsIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedPortalInboxRoute: typeof AuthenticatedPortalInboxRoute
  AuthenticatedPortalIndexRoute: typeof AuthenticatedPortalIndexRoute
  AuthenticatedPortalClientsIdRoute: typeof AuthenticatedPortalClientsIdRoute
  AuthenticatedPortalLibraryIdRoute: typeof AuthenticatedPortalLibraryIdRoute
  AuthenticatedPortalClientsIndexRoute: typeof AuthenticatedPortalClientsIndexRoute
  AuthenticatedPortalLibraryIndexRoute: typeof AuthenticatedPortalLibraryIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedPortalInboxRoute: AuthenticatedPortalInboxRoute,
  AuthenticatedPortalIndexRoute: AuthenticatedPortalIndexRoute,
  AuthenticatedPortalClientsIdRoute: AuthenticatedPortalClientsIdRoute,
  AuthenticatedPortalLibraryIdRoute: AuthenticatedPortalLibraryIdRoute,
  AuthenticatedPortalClientsIndexRoute: AuthenticatedPortalClientsIndexRoute,
  AuthenticatedPortalLibraryIndexRoute: AuthenticatedPortalLibraryIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AboutRoute: AboutRoute,
  AuthRoute: AuthRoute,
  ContactRoute: ContactRoute,
  GuaranteeRoute: GuaranteeRoute,
  HowItWorksRoute: HowItWorksRoute,
  PricingRoute: PricingRoute,
  PrivacyRoute: PrivacyRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TermsRoute: TermsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
